AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Gemspec/RequiredRubyVersion:
  Enabled: false

# RSpec describe blocks are supposed to be longer than regular blocks
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'