name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }}
    strategy:
      matrix:
        suite:
          - rspec
          - rubocop
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1.0"

    - name: bundle install
      run: bundle install

    - name: run ${{ matrix.suite }}
      run: ${{ matrix.suite }}